config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'new_participant' => 'participants#new'
  resources :participants
  resources :services
  resources :studies
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :participant
  belongs_to :service
end

app/models/focus.rb
class Focus < ActiveRecord::Base
  belongs_to :study
  belongs_to :service
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  has_many :experiences
  has_many :services, through: :experiences
  has_many :sessions
  has_many :studies, through: :sessions
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 100 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :experiences
  has_many :participants, through: :experiences
  has_many :focus
  has_many :studies, through: :focus
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :participant
  belongs_to :study
end

app/models/study.rb
class Study < ActiveRecord::Base
  has_many :sessions
  has_many :participants, through: :sessions
  has_many :focus
  has_many :services, through: :focus
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "hello, world!"
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def show
  	@participant = Participant.find(params[:id])
  end

  def new
  	@participant = Participant.new
  end

  def create
    @participant = Participant.new(participant_params)
    if @participant.save
      flash[:success] = "Participant created."
      redirect_to @participant
    else
      render 'new'
    end
  end

  def edit
  	@participant = Participant.find(params[:id])
  end

  def update
    @participant = Participant.find(params[:id])
    if @participant.update_attributes(participant_params)
      flash[:success] = "Participant updated."
      redirect_to @participant
    else
      render 'edit'
    end
  end

  def index
  	@participants = Participant.all
  end

  def destroy
    Participant.find(params[:id]).destroy
    flash[:success] = "Participant deleted."
    redirect_to participants_url
  end

  private

    def participant_params
      params.require(:participant).permit(:name, :email, :company, :role, :city)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def show
  	@service = Service.find(params[:id])
  end

  def new
  	@service = Service.new
  end

  def create
    @service = Service.new(service_params)
    if @service.save
      flash[:success] = "Service created."
      redirect_to @service
    else
      render 'new'
    end
  end

  def edit
  	@service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    if @service.update_attributes(service_params)
      flash[:success] = "Service updated."
      redirect_to @service
    else
      render 'edit'
    end
  end

  def index
  	@services = Service.all
  end

  def destroy
    service.find(params[:id]).destroy
    flash[:success] = "Service deleted."
    redirect_to services_url
  end

  private

    def service_params
      params.require(:service).permit(:name)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Participants", participants_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/participants/_participant.html.erb
<li>
  <%= link_to participant.name, participant %>
  <%= link_to "Edit", edit_participant_path(participant) %>
  <%= link_to "Delete", participant, method: :delete,
                                  data: { confirm: "You sure?" } %>
</li>

app/views/participants/edit.html.erb
<% provide(:title, "Edit participant") %>
<h1>Edit participant</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@participant) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :company %>
      <%= f.text_field :company, class: 'form-control' %>

      <%= f.label :role %>
      <%= f.text_field :role, class: 'form-control' %>

      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/participants/index.html.erb
<% provide(:title, 'Participants') %>
<h1>Participants</h1>

<%= link_to "Create new participant", new_participant_path %>

<ul class="participants">
  <%= render @participants %>
</ul>

app/views/participants/new.html.erb
<% provide(:title, 'New participant') %>
<h1>Create new participant</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@participant) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :company %>
      <%= f.text_field :company, class: 'form-control' %>

      <%= f.label :role %>
      <%= f.text_field :role, class: 'form-control' %>

      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/participants/show.html.erb
<% provide(:title, @participant.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="participant_info">
      <h1>
        <%= @participant.name %>
      </h1>
    </section>
  </aside>
  Services Used:
  <ul>
    <% @participant.services.each do |service| %>
      <li><%= service.name %></li>
    <% end %>
  </ul>
</div>

app/views/services/_service.html.erb
<li>
  <%= link_to service.name, service %>
  <%= link_to "Edit", edit_service_path(service) %>
  <%= link_to "Delete", service, method: :delete,
                                  data: { confirm: "You sure?" } %>
</li>

app/views/services/edit.html.erb
<% provide(:title, "Edit service") %>
<h1>Edit service</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@service) do |f| %>
      <%= render 'shared/service_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/services/index.html.erb
<% provide(:title, 'Services') %>
<h1>Services</h1>

<%= link_to "Create new service", new_service_path %>

<ul class="services">
  <%= render @services %>
</ul>

app/views/services/new.html.erb
<% provide(:title, 'New service') %>
<h1>Create new service</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@service) do |f| %>
      <%= render 'shared/service_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/services/show.html.erb
<% provide(:title, @service.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="service_info">
      <h1>
        <%= @service.name %>
      </h1>
    </section>
  </aside>
  Participants Using:
  <ul>
    <% @service.participants.each do |participant| %>
      <li><%= participant.name %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_error_messages.html.erb
<% if @participant.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@participant.errors.count, "error") %>.
    </div>
    <ul>
    <% @participant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_service_error_messages.html.erb
<% if @service.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@service.errors.count, "error") %>.
    </div>
    <ul>
    <% @service.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    Words!
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>